# Generated by Django 4.2.2 on 2023-07-12 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_atleta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
